[package]
name = "CedraMiniApp"
version = "1.0.0"
authors = ["Cedra GameFi Team"]

[addresses]
cedra_gamefi = "79ca407a19d76dcc4f722fb074781afd1a3a7316520295e4969673a81a0dabfe"
game_admin = "79ca407a19d76dcc4f722fb074781afd1a3a7316520295e4969673a81a0dabfe"

[dev-addresses]



[dependencies]
CedraFramework = { git = "https://github.com/cedra-labs/cedra-framework.git", subdir = "cedra-framework", rev = "main" }